import {useEffect,useState} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const[token, setToken] = useState(null)

  useEffect(() => {

    window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
      window.flutter_inappwebview.callHandler('getToken').then(function(result) { 
        const jsonToken = JSON.parse(result)
        console.log('RESULT', result);
        setToken(jsonToken)  
      });      
    });

  }, [])

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {
            token === null ? 'You need token to get access Webview!' : 'Welcome to Webview!'
          }
          
        </h1>
        
      </main>
      
    </div>
  )
}
