import {useEffect,useState} from 'react'

function App() {
  const[token, setToken] = useState(null)

  useEffect(() => {
    
    window.addEventListener("flutterInAppWebViewPlatformReady", function(event) {
      window.flutter_inappwebview.callHandler('getToken').then(function(result) { 
        const jsonToken = JSON.parse(result)
        setToken(jsonToken)  
      });      
    });

  }, [])

  useEffect(() => {
    console.log('Token', token);
  }, [token])

  return (
    <div >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      <main>
        <h1>
          {
            token === null ? 'You need token to get access Wsebview!' : 'Welcome to Webview!'
          }
          
          <button onclick="javascript:alert('aaa')">abcdef</button>
        </h1>
        
      </main>
    </div>
  )
}

export default App;
